<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <RockWebPath>..\..\Rock\RockWeb</RockWebPath>
    <AdditionalAssembliesToCopy>Microsoft.Graph.Core.dll;Microsoft.Graph.dll;Microsoft.Kiota.Abstractions.dll;Microsoft.Kiota.Authentication.Azure.dll;Microsoft.Kiota.Http.HttpClientLibrary.dll;Microsoft.Kiota.Serialization.Form.dll;Microsoft.Kiota.Serialization.Json.dll;Microsoft.Kiota.Serialization.Multipart.dll;Microsoft.Kiota.Serialization.Text.dll;System.Net.Http.WinHttpHandler.dll;Std.UriTemplate.dll;</AdditionalAssembliesToCopy>
    <CopyToRockWeb>true</CopyToRockWeb>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis" Version="1.73.0" />
    <PackageReference Include="Google.Apis.Admin.Directory.directory_v1" Version="1.73.0.4030" />
    <PackageReference Include="Google.Apis.Calendar.v3" Version="1.73.0.3993" />
    <PackageReference Include="Microsoft.Owin" Version="4.2.2" />
    <PackageReference Include="SparkDevNetwork.Rock.Build.Tasks" Version="1.0.4" />
    <PackageReference Include="SparkDevNetwork.Rock.Analyzers" Version="1.0.4" />
    <PackageReference Include="RockRMS.Rock" Version="17.6.1" />
    <PackageReference Include="RockRMS.Rock.Blocks" Version="17.6.1" />
    <PackageReference Include="RockRMS.Rock.Rest" Version="17.6.1" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.2.3" />


    <PackageReference Include="Azure.Core" Version="1.44.1" />
    <PackageReference Include="Azure.Identity" Version="1.12.0" />

    <PackageReference Include="Microsoft.Graph" Version="5.56.0" />
    <PackageReference Include="Microsoft.Graph.Core" Version="3.1.14" />
    <PackageReference Include="Microsoft.Kiota.Abstractions" Version="1.9.11" />
    <PackageReference Include="Microsoft.Kiota.Authentication.Azure" Version="1.9.11" />
    <PackageReference Include="Microsoft.Kiota.Http.HttpClientLibrary" Version="1.9.11" />
    <PackageReference Include="Microsoft.Kiota.Serialization.Form" Version="1.9.11" />
    <PackageReference Include="Microsoft.Kiota.Serialization.Json" Version="1.9.11" />
    <PackageReference Include="Microsoft.Kiota.Serialization.Multipart" Version="1.9.11" />
    <PackageReference Include="Microsoft.Kiota.Serialization.Text" Version="1.9.11" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DotLiquid">
      <HintPath>..\..\Rock\RockWeb\Bin\DotLiquid.dll</HintPath>
    </Reference>
    <Reference Include="EntityFramework">
      <HintPath>..\..\Rock\RockWeb\Bin\EntityFramework.dll</HintPath>
    </Reference>
    <Reference Include="EntityFramework.SqlServer">
      <HintPath>..\..\Rock\RockWeb\Bin\EntityFramework.SqlServer.dll</HintPath>
    </Reference>
    <Reference Include="Ical.Net">
      <HintPath>..\..\Rock\RockWeb\Bin\Ical.Net.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\Rock\RockWeb\Bin\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="PuppeteerSharp">
      <HintPath>..\..\Rock\RockWeb\Bin\PuppeteerSharp.dll</HintPath>
    </Reference>
    <Reference Include="Quartz">
      <HintPath>..\..\Rock\RockWeb\Bin\Quartz.dll</HintPath>
    </Reference>
    <Reference Include="Rock.Lava">
      <HintPath>..\..\Rock\RockWeb\Bin\Rock.Lava.dll</HintPath>
    </Reference>
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="TimeZoneConverter">
      <HintPath>..\..\Rock\RockWeb\Bin\TimeZoneConverter.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Model\SchedulingProvider\" />
  </ItemGroup>

</Project>
