<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <RockWebPath>..\..\Rock\RockWeb</RockWebPath>
    <AdditionalAssembliesToCopy></AdditionalAssembliesToCopy>
    <CopyToRockWeb>true</CopyToRockWeb>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Owin" Version="4.2.2" />
    <PackageReference Include="SparkDevNetwork.Rock.Build.Tasks" Version="1.0.4" />
    <PackageReference Include="SparkDevNetwork.Rock.Analyzers" Version="1.0.4" />
    <PackageReference Include="RockRMS.Rock" Version="17.6.1" />
    <PackageReference Include="RockRMS.Rock.Blocks" Version="17.6.1" />
    <PackageReference Include="RockRMS.Rock.Rest" Version="17.6.1" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DotLiquid">
      <HintPath>..\..\Rock\RockWeb\Bin\DotLiquid.dll</HintPath>
    </Reference>
    <Reference Include="EntityFramework">
      <HintPath>..\..\Rock\RockWeb\Bin\EntityFramework.dll</HintPath>
    </Reference>
    <Reference Include="EntityFramework.SqlServer">
      <HintPath>..\..\Rock\RockWeb\Bin\EntityFramework.SqlServer.dll</HintPath>
    </Reference>
    <Reference Include="Ical.Net">
      <HintPath>..\..\Rock\RockWeb\Bin\Ical.Net.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\Rock\RockWeb\Bin\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="PuppeteerSharp">
      <HintPath>..\..\Rock\RockWeb\Bin\PuppeteerSharp.dll</HintPath>
    </Reference>
    <Reference Include="Quartz">
      <HintPath>..\..\Rock\RockWeb\Bin\Quartz.dll</HintPath>
    </Reference>
    <Reference Include="Rock.Lava">
      <HintPath>..\..\Rock\RockWeb\Bin\Rock.Lava.dll</HintPath>
    </Reference>
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="TimeZoneConverter">
      <HintPath>..\..\Rock\RockWeb\Bin\TimeZoneConverter.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
